- name: Be sure swap is off
  shell: /usr/sbin/swapoff -a
  tags: node_join
- name: Be sure selinux is off
  selinux: state=disabled
  tags: node_join
- name: Stop and disable firewall
  service: name=firewalld state=stopped enabled=no
  tags: node_join
- name: Set sysctl file
  copy: src=k8s.conf dest=/etc/sysctl.d/k8s.conf
  tags: node_join
- name: Make up sysctl file
  shell: sysctl --system
  tags: node_join
- name: Be sure docker,kubeadm,kubelet is installed
  yum: name={{item}} state=latest
  with_items:
        - docker-ce
        - kubeadm-{{version}}
        - kubelet-{{version}}
  tags: node_join
- name: create docker config file
  shell: mkdir -pv /etc/docker/
  tags: node_join
- name: harbor
  template: src=daemon.j2 dest=/etc/docker/daemon.json
  tags: node_join
- name: restart docker
  service: name=docker state=restarted enabled=yes
  with_items:
         - docker
         - kubelet
  tags: node_join
